### ISSUE TITLE
ValueError: stat: embedded null character in path

### ISSUE THREAD

**Issue by YuGong123** [StelaBou/StyleMask#13]
----- Load generator from ./pretrained_models/stylegan2-ffhq-config-f_1024.pt -----
----- Load mask network from ./pretrained_models/mask_network_1024.pt -----
----- Load e4e encoder from ./pretrained_models/e4e_ffhq_encode_1024.pt -----
Reenact 1 pairs
  0% 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "run_inference.py", line 305, in <module>
    main()
  File "run_inference.py", line 299, in main
    inf.run()
  File "run_inference.py", line 220, in run
    source_img = image_to_tensor(cropped_image).unsqueeze(0).cuda()
  File "/content/StyleMask/libs/utilities/image_utils.py", line 18, in image_to_tensor
    if os.path.isfile(image_file):
  File "/usr/local/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: embedded null character in path

How can we solve this problem?

**Comment by YuGong123** [comment]
def image_to_tensor(image_file):
	max_val = 1
	min_val = -1
	if os.path.isfile(image_file):
		image = cv2.imread(image_file, cv2.IMREAD_COLOR) # BGR order
		image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype('uint8')
	else:
		image = image_file
	if image.shape[0]>256:
		image, _ = image_resize(image, 256)
	image_tensor = torch.tensor(np.transpose(image,(2,0,1))).float().div(255.0)	
	image_tensor = image_tensor * (max_val - min_val) + min_val

	return image_tensor


---------------------------------》
def image_to_tensor(image_file):
	max_val = 1
	min_val = -1

	image = image_file
	if image.shape[0]>256:
		image, _ = image_resize(image, 256)
	image_tensor = torch.tensor(np.transpose(image,(2,0,1))).float().div(255.0)	
	image_tensor = image_tensor * (max_val - min_val) + min_val

	return image_tensor

**Comment by StelaBou** [comment]
What is the type of variable `cropped_image` in line 220 ?
`source_img = image_to_tensor(cropped_image).unsqueeze(0).cuda()`

**Comment by YuGong123** [comment]
> What is the type of variable `cropped_image` in line 220 ? `source_img = image_to_tensor(cropped_image).unsqueeze(0).cuda()`

tensor

**Comment by YuGong123** [comment]
> What is the type of variable `cropped_image` in line 220 ? `source_img = image_to_tensor(cropped_image).unsqueeze(0).cuda()`

tensor, not file path

**Comment by StelaBou** [comment]
I fixed it, thank you.
