### ISSUE TITLE
AttributeError: _2D

### ISSUE THREAD

**Issue by SmileShaun** [StelaBou/StyleMask#15]
Traceback (most recent call last):
  File "run_inference.py", line 309, in <module>
    main()
  File "run_inference.py", line 303, in main
    inf.run()
  File "run_inference.py", line 212, in run
    self.load_models(inversion)
  File "run_inference.py", line 100, in load_models
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cuda')
  File "/root/anaconda3/envs/StyleMask/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by StelaBou** [comment]
Please change `self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cuda')`  to  `self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, device='cuda')` .
See also [here]( https://stackoverflow.com/questions/76651887/am-facing-attributeerror2d-how-do-i-resolve-it).
