### ISSUE TITLE
[Error] embedded null character in path

### ISSUE THREAD

**Issue by Loc-VD** [StelaBou/StyleMask#3]
I tried some real images with additional param --source_path and --target_path then got the following error message:
```
----- Load generator from ./pretrained_models/stylegan2-ffhq-config-f_1024.pt -----
----- Load mask network from ./pretrained_models/mask_network_1024.pt -----
----- Load e4e encoder from ./pretrained_models/e4e_ffhq_encode_1024.pt -----
Reenact 1 pairs
  0% 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "run_inference.py", line 305, in <module>
    main()
  File "run_inference.py", line 299, in main
    inf.run()
  File "run_inference.py", line 220, in run
    source_img = image_to_tensor(cropped_image).unsqueeze(0).cuda()
  File "/content/StyleMask/libs/utilities/image_utils.py", line 18, in image_to_tensor
    if os.path.isfile(image_file):
  File "/usr/local/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: embedded null character in path
```

**Comment by StelaBou** [comment]
Could you share the source and target paths that gave you this error message? Could you also print the value of cropped_image (line 219) ? 
Maybe the problem is on the preprocessing step (line 219):
 `cropped_image = preprocess_image(source_samples[i], self.fa, save_filename = None)`
